apiVersion: v1
kind: Service
metadata:
  name: backend-service
  
spec:
  selector:
    app: backend-nodejs
  type: NodePort
  ports:
  - name: backend-deployment
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001

