services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: notes
    ports:
      - 5432:5432
    networks:
      - web-app
    volumes:
      - web-server-db-volume:/var/lib/postgresql/data

  server:
    build: ./server/ 
    environment:
      DATABASE_HOST: db  
      DATABASE_PORT : 5432
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_NAME: notes
    depends_on:
      - db
    ports: 
      - 3000:3000
    networks:
     - web-app

networks:
  web-app:
    driver: bridge

volumes:
  web-server-db-volume:
    external: true
