name: web-app-CI

on: 
  push:
    branches: [ setup-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install and test server
      - run:
          cd server 
          npm ci 
          #npm run lint  
      
      - name: Install and test client
      - run: 
          cd client 
          npm ci 
          npm run lint
          

